---
# CAT I Findings

# V-38677 can be found in not_automated.yml

- name: "HIGH | V-38491 | AUDIT | There must be no hosts.equiv on the system"
  stat:
      path: /etc/hosts.equiv
  register: hosts_equiv_audit
  failed_when: "hosts_equiv_audit.stat.exists is defined and hosts_equiv_audit.stat.exists == True"
  changed_when: no
  ignore_errors: yes
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38491
    - hosts_equiv

- name: "HIGH | V-38491 | PATCH | There must be no hosts.equiv on the system"
  file:
      state: absent
      dest: /etc/hosts.equiv
  when: hosts_equiv_audit.failed
  tags:
    - high
    - cat1
    - patch
    - V-38491
    - hosts_equiv

- name: "HIGH | V-38491 | AUDIT | There must be no .rhosts files on the system"
  stat:
      path: ~{{ item }}/.rhosts
  with_items: users.stdout_lines
  register: rhosts_audit
  failed_when: "rhosts_audit.stat.exists is defined and rhosts_audit.stat.exists == True"
  changed_when: no
  ignore_errors: yes
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38491
    - hosts_equiv

- name: "HIGH | V-38491 | PATCH | There must be no .rhosts files on the system"
  file:
    state: absent
    dest: ~{{ item }}/.rhosts
  with_items: users.stdout_lines
  when: rhosts_audit|failed
  tags:
    - high
    - cat1
    - patch
    - V-38491
    - rhosts

# Todo: authconfig in CentOS7? /etc/pam.d/system-auth-ac?
- name: "HIGH | V-38497 | AUDIT | The system must not have accounts configured with blank or null passwords"
  command: grep nullok /etc/pam.d/system-auth
  register: nullok_audit
  failed_when: nullok_audit.stdout_lines|length > 0
  changed_when: no
  ignore_errors: yes
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38497
    - passwords

- name: "HIGH | V-38497 | PATCH | The system must not have accounts configured with blank or null passwords"
  replace:
      dest: /etc/pam.d/system-auth
      regexp: nullok
  when: nullok_audit.failed
  tags:
    - high
    - cat1
    - patch
    - V-38497
    - passwords

- name: "HIGH | V-38587 | AUDIT | The telnet-server package must not be installed"
  command: rpm -q telnet-server
  register: telnet_server_audit
  failed_when: "'is not installed' not in telnet_server_audit.stdout"
  changed_when: no
  ignore_errors: yes
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38587
    - telnet
    - unsecure_services

- name: "HIGH | V-38587 | PATCH | The telnet-server package must not be installed"
  yum:
    name: telnet-server
    state: absent
  when: telnet_server_audit.failed
  tags:
    - high
    - cat1
    - patch
    - V-38587
    - telnet
    - unsecure_services

- name: "HIGH | V-38589 | AUDIT | The telnet daemon must not be running"
  command: /usr/bin/systemctl is-enabled telnet.socket
  register: telnet_service_audit
  failed_when: "'No such file or directory' not in telnet_service_audit.stderr"
  changed_when: no
  ignore_errors: yes
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38589
    - telnet
    - unsecure_services

- name: "HIGH | V-38589 | PATCH | The telnet daemon must not be running"
  service:
    name: telnet.socket
    state: stopped
    enabled: no
  when: telnet_service_audit.failed
  tags:
    - high
    - cat1
    - patch
    - V-38589
    - telnet
    - unsecure_services

- name: "HIGH | V-38591 | AUDIT | The rsh-server package must not be installed"
  command: rpm -q rsh-server
  register: rsh_server_audit
  failed_when: "'is not installed' not in rsh_server_audit.stdout"
  changed_when: no
  ignore_errors: yes
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38591
    - rsh
    - unsecure_services

- name: "HIGH | V-38591 | PATCH | The rsh-server package must not be installed"
  yum:
    name: rsh-server
    state: absent
  when: rsh_server_audit.failed
  tags:
    - high
    - cat1
    - patch
    - V-38591
    - rsh
    - unsecure_services

- name: "HIGH | V-38594 | AUDIT | The rshd service must not be running"
  command: /usr/bin/systemctl is-enabled rsh.socket
  register: rsh_service_audit
  failed_when: "'No such file or directory' not in rsh_service_audit.stderr"
  ignore_errors: yes
  changed_when: no
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38594
    - rsh
    - rlogin
    - unsecure_services

- name: "HIGH | V-38594 | PATCH | The rshd service must not be running"
  service:
    name: rsh.socket
    state: stopped
    enabled: no
  when: rsh_service_audit.failed
  tags:
    - high
    - cat1
    - patch
    - V-38594
    - rsh
    - rlogin
    - unsecure_services

- name: "HIGH | V-38598 | AUDIT | The rexecd service must not be running"
  command: /usr/bin/systemctl is-enabled rexec.socket
  register: rexec_status_audit
  failed_when: "'No such file or directory' not in rexec_status_audit.stderr"
  changed_when: no
  ignore_errors: yes
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38598
    - rexec

- name: "HIGH | V-38598 | PATCH | The rexecd service must not be running"
  service:
      name: rexec
      state: stopped
  when: rexec_status_audit.failed
  tags:
    - high
    - cat1
    - patch
    - V-38598
    - rexec

- name: "HIGH | V-38602 | AUDIT | The rlogind service must not be running"
  command: /usr/bin/systemctl is-enabled rlogin.socket
  register: rlogin_status_audit
  failed_when: "'No such file or directory' not in rlogin_status_audit.stderr"
  changed_when: no
  ignore_errors: yes
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38602
    - rlogin

- name: "HIGH | V-38602 | PATCH | The rlogind service must not be running"
  service:
    name: rlogin
    enabled: no
  when: rlogin_status_audit.failed
  tags:
    - high
    - cat1
    - patch
    - V-38602
    - rlogin

- name: "HIGH | V-38607 | AUDIT | The SSH daemon must be configured to use only the SSHv2 protocol\n
     \t\tHIGH | V-38614 | AUDIT | The SSH daemon must not allow authentication using an empty password"
  command: grep "^{{ item.ln }}" /etc/ssh/sshd_config
  ignore_errors: yes
  changed_when: no
  register: cat1_sshd_config_audit
  with_items:
      - { ref: 'V-38607' , st: 'present', rx: '^(#)?Protocol \d', ln: 'Protocol 2' }
      - { ref: 'V-38614' , st: 'present', rx: '^(#)?PermitEmptyPasswords', ln: 'PermitEmptyPasswords no' }
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38607
    - V-38614
    - ssh

- name: "HIGH | V-38607 | PATCH | The SSH daemon must be configured to use only the SSHv2 protocol\n
     \t\tHIGH | V-38614 | PATCH | The SSH daemon must not allow authentication using an empty password"
  lineinfile:
      state: '{{ item.st }}'
      regexp: '{{ item.rx }}'
      line: '{{ item.ln }}'
      dest: /etc/ssh/sshd_config
  with_items:
      - { ref: 'V-38607' , st: 'present', rx: '^(#)?Protocol \d', ln: 'Protocol 2' }
      - { ref: 'V-38614' , st: 'present', rx: '^(#)?PermitEmptyPasswords', ln: 'PermitEmptyPasswords no' }
  notify: restart ssh
  when: cat1_sshd_config_audit|failed
  tags:
    - high
    - cat1
    - patch
    - V-38607
    - V-38614
    - ssh

- name: "HIGH | V-38668 | AUDIT | The x86 Ctrl-Alt-Delete key sequence must be disabled"
  stat:
      path: /usr/lib/systemd/system/ctrl-alt-del.target
  register: ctrl_alt_del_audit
  failed_when: "ctrl_alt_del_audit.stat.islnk is defined and ctrl_alt_del_audit.stat.islnk == False or ctrl_alt_del_audit.stat.lnk_source != '/dev/null'"
  changed_when: no
  ignore_errors: yes
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38668
    - ctrl_alt_delete

- name: "HIGH | V-38668 | PATCH | The x86 Ctrl-Alt-Delete key sequence must be disabled"
  file:
      dest: /usr/lib/systemd/system/ctrl-alt-del.target
      src: /dev/null
      state: link
  when: ctrl_alt_del_audit.failed
  tags:
    - high
    - cat1
    - patch
    - V-38668
    - ctrl_alt_delete

- name: "HIGH | V-38701 | AUDIT | The TFTP daemon must operate in secure mode which provides access only to a single directory on the host file system"
  command: grep "server_args = -s" /etc/xinetd.d/tftp
  register: tftp_audit
  when: "'tftp' in xinetd_services.stdout_lines"
  changed_when: no
  ignore_errors: yes
  tags:
    - high
    - cat1
    - audit
    - always
    - V-38701
    - tftp

- name: "HIGH | V-38701 | PATCH | The TFTP daemon must operate in secure mode which provides access only to a single directory on the host file system"
  lineinfile:
      state: present
      dest: /etc/xinetd.d/tftp
      regexp: 'server_args\\s+=\\s+(/.*$)'
      line: '\tserver_args\t\t= -s \\1'
      backrefs: yes
  notify: reload xinetd
  when: "cent7stig_tftp_required and 'tftp' in xinetd_services.stdout_lines and tftp_audit.failed"
  tags:
    - high
    - cat1
    - patch
    - V-38701
    - tftp
    - tftp-server
    - unsecure_services

