---
- name: V-38612 Medium  The SSH daemon must not allow host-based authentication
  lineinfile: state=present dest=/etc/ssh/sshd_config regexp='^(#)?HostbasedAuthentication' line='HostbasedAuthentication no'
  tags: [ 'ssh' , 'cat2' ]
  notify: restart ssh


# This audit.rules file is from https://github.com/RedHatGov/stig-fix-el6/tree/master/config
# I modified it slightly by turning it into a template
- name: V-38580 Medium  Copy STIG compliant audit.rules
  template: src=audit.rules.j2 dest=/etc/audit/audit.rules owner=root group=root mode=0640 backup=yes
  tags: cat2
  notify: restart auditd


- name: V-38459 Medium  The /etc/group file must be group-owned by root
  file: dest=/etc/group owner=root group=root mode=0644
  tags: cat2


# Search for world writable files and print them out if any are found
- name: V-38643 Medium  There must be no world-writable files on the system
  command: find / -xdev -type f -perm -002
  register: world_writable_files
  tags: cat2

- name: The following files are world writable. This is a finding.
  debug: var=world_writable_files.stdout_lines
  when: world_writable_files.stdout_lines
  tags: cat2

- name: V-38643 Medium  There must be no world-writable files on the system
  pause: prompt="World writable files are present on the system. This is a finding. Press Enter to continue."
  when: world_writable_files.stdout_lines and not fullauto
  tags: cat2


# See if IPv6 is enabled before enabling ip6tables
- name: Check if IPv6 is enabled
  shell: ip addr | grep inet6
  register: ipv6test
  ignore_errors: yes
  tags: cat2

- name: V-38551 Medium  The operating system must connect to external networks or information systems only through managed IPv6 interfaces consisting of boundary protection devices arranged in accordance with an organizational security architecture
  service: name=ip6tables enabled=yes state=started
  when: ipv6test.stdout
  ignore_errors: yes
  tags: cat2


# Look in /etc/password for hashes and print them out if any are found
- name: V-38499 Medium  The /etc/passwd file must not contain password hashes
  shell: "awk -F: '($2 != \"x\") {print}' /etc/passwd"
  register: etc_password_hash_check
  ignore_errors: yes
  tags: cat2

- name: The following password hashes were found in /etc/passwd. This is a finding.
  debug: var=etc_password_hash_check.stdout_lines
  when: etc_password_hash_check.stdout
  tags: cat2

- name: V-38499 Medium  The /etc/passwd file must not contain password hashes
  pause: prompt="The following password hashes were found in /etc/passwd. This is a finding. Press Enter to continue."
  when: etc_password_hash_check.stdout and not fullauto
  tags: cat2


- name: V-38450 V-38451 Medium  The /etc/passwd file must be owned and group owned by root
  file: path=/etc/passwd owner=root group=root mode=0644
  tags: cat2

- name: V-38581 Medium  The system boot loader configuration file(s) must be group-owned by root
  file: path=/boot/grub/grub.conf owner=root group=root mode=0600
  tags: cat2

- name: V-38458 Medium  The /etc/group file must be owned by root
  file: path=/etc/group owner=root group=root mode=0644
  tags: cat2

- name: V-38658 Medium  The system must prohibit the reuse of passwords within twenty-four iterations
  lineinfile: state=present dest=/etc/pam.d/system-auth regexp='(password\s+sufficient\s+pam_unix.so)' line='\1 sha512 shadow nullok try_first_pass use_authtok remember=24' backrefs=yes backup=yes
  tags: cat2


# List all xinetd services then look for 'on' in the output
# If any xinted service is found to be on, skip these tasks since xinetd can be on if a service is using it
- name: Checking if any xinetd services are enabled
  shell: "chkconfig --list | sed -n '/xinetd based services/,$p'"
  register: xinetd_services
  tags: cat2

- name: V-38582 Medium  The xinetd service must be disabled if no network services utilizing it are enabled
  service: name=xinetd enabled=no state=stopped
  ignore_errors: yes
  when: xinetd_services.stdout.find('\ton\n') == -1
  tags: cat2


# List nfs mounts that are missing the nodev option and ask the sys admin to correct this in /etc/fstab
# This would be a bit tricky to automatically fix in /etc/fstab.
- name: Checking for nfs mounts missing the 'nodev' option
  shell: mount | grep 'type nfs' | grep -v 'nodev'
  ignore_errors: yes
  register: nfs_mounts_missing_nodev
  tags: cat2

- name: V-38652 Medium  Remote file systems must be mounted with the 'nodev' option
  debug: var=nfs_mounts_missing_nodev.stdout_lines
  when: nfs_mounts_missing_nodev.stdout
  tags: cat2

- name: V-38652 Medium  Remote file systems must be mounted with the 'nodev' option
  pause: prompt="There are nfs mounts without the 'nodev' option set. This is a finding. Press Enter to continue."
  when: nfs_mounts_missing_nodev.stdout and not fullauto
  tags: cat2


# List nfs mounts that are missing the 'nosuid' option and ask the sys admin to correct this in /etc/fstab
# This would be a bit tricky to automatically fix in /etc/fstab.
- name: Checking for nfs mounts missing the 'nosuid' option
  shell: mount | grep 'type nfs' | grep -v 'nosuid'
  ignore_errors: yes
  register: nfs_mounts_missing_nosuid
  tags: cat2

- name: V-38652 Medium  Remote file systems must be mounted with the nosuid option
  debug: var=nfs_mounts_missing_nosuid.stdout_lines
  when: nfs_mounts_missing_nosuid.stdout
  tags: cat2

- name: V-38652 Medium  Remote file systems must be mounted with the nosuid option
  pause: prompt="There are nfs mounts without the 'nosuid' option set. This is a finding. Press Enter to continue."
  when: nfs_mounts_missing_nosuid.stdout and not fullauto
  tags: cat2


- name: V-38490 Medium  The operating system must enforce requirements for the connection of mobile devices to operating systems
  kernel_blacklist: name=usb-storage
  notify: unload usb-storage
  tags: cat2

- name: V-38443 Medium  The /etc/gshadow file must be owned by root
  file: path=/etc/gshadow owner=root group=root mode=0000
  tags: cat2

- name: V-38526 Medium  The system must not accept ICMPv4 secure redirect packets on any interface
  sysctl: name=net.ipv4.conf.all.secure_redirects value=0 state=present reload=yes ignoreerrors=yes
  tags: cat2

- name: V-38524 Medium  The system must not accept ICMPv4 redirect packets on any interface
  sysctl: name=net.ipv4.conf.all.accept_redirects value=0 state=present reload=yes ignoreerrors=yes
  tags: cat2

# - name: V-38488 Medium  The operating system must conduct backups of user-level information contained in the operating system per organization defined frequency to conduct backups consistent with recovery time and recovery point objectives

- name: Checking for remote log servers
  shell: grep -Er '(^[^#]?\*\.\*\s+@{1,2})|(\*\.\*\s+omrelp)' /etc/rsyslog.conf /etc/rsyslog.d/
  ignore_errors: yes
  register: remote_logging_servers
  tags: cat2

- name: V-38520 Medium  The operating system must back up audit records on an organization defined frequency onto a different system or media than the system being audited
  pause: prompt="No remote logging server is configured. Press Enter to continue."
  when: not remote_logging_servers.stdout and not fullauto
  tags: cat2

