---
- name: V-38649 Low  The system default umask for the csh shell must be 077
  replace: backup=yes dest=/etc/csh.cshrc regexp="umask \d\d\d" replace="umask 077"
  tags: [ 'cat3' , 'V-38649' , 'csh' , 'umask' ]

- name: V-38642 Low  The system default umask for daemons must be 027 or 022
  lineinfile: state=present backup=yes dest=/etc/init.d/functions regexp="umask \d\d\d" line="umask 022"
  tags: [ 'cat3' , 'V-38642' , 'umask' ]

- name: "V-38648 Low  The qpidd service must not be running\n    V-38641 Low  The atd service must be disabled\n    V-38640 Low  The Automatic Bug Reporting Tool (abrtd) service must not be running\n    V-38646 Low  The oddjobd service must not be running\n    V-38644 Low  The ntpdate service must not be running\n    V-38650  Low The rdisc service must not be running"
  service: name={{ item.name }} state={{ item.state }} enabled={{ item.enabled }}
  when: "'{{ item.name }}' in sysv_services.stdout_lines"
  with_items: rhel6stig_cat3_disabled_services
  tags: [ 'cat3' , 'V-38640' , 'abrtd', 'V-38648' , 'qpidd' , 'V-38641' , 'atd' , 'V-38646' , 'oddjobd' , 'V-38644' , 'ntpdate' , 'V-38650' , 'rdisc' ]

- name: V-38647 Low  The system default umask in /etc/profile must be 077
  replace: backup=yes dest={{ item }} regexp="umask \d\d\d" replace="umask 077"
  with_items:
    - /etc/profile
    - /etc/bashrc
  tags: [ 'cat3' , 'V-38647' , 'umask' , 'bash' ]


# Set default umask for fish shell if it is installed
# This required two tasks in order to add multiple lines cleanly
# Adding '\n' to the 'line' field causes this module to reinsert the same
# line every time the task is run which is very undesirable.
- name: Set default umask for fish shell to 077
  lineinfile: backup=yes dest=/etc/fish/config.fish line="# Set default umask" insertafter=EOF
  when: '"fish" in shells.stdout_lines'
  tags: [ 'cat3' , 'V-38647' , 'umask' , 'bash' ]

- name: Set default umask for fish shell to 077
  lineinfile: backup=yes dest=/etc/fish/config.fish line="umask 077" insertafter="# Set default umask"
  when: '"fish" in shells.stdout_lines'
  tags: [ 'cat3' , 'V-38647' , 'umask' , 'bash' ]


- name: V-38645 Low  The system default umask in /etc/login.defs must be 077
  lineinfile: "state=present backup=yes dest=/etc/login.defs regexp='^UMASK' line='UMASK           077'"
  tags: [ 'cat3' , 'V-38645' , 'umask' ]

- name: V-51369 Low  The system must use a Linux Security Module configured to limit the privileges of system services
  selinux: policy=targeted state=enforcing
  tags: [ 'cat3' , 'V-51369' , 'selinux' ]


- name: Check permissions on all files and directories associated with packages
  shell: "grep '^.M' /tmp/rhel6stig_rpm_verify | awk '{print $3}' "
  changed_when: false
  register: rpm_file_permissions_check
  failed_when: rpm_file_permissions_check.stderr
  tags: [ 'cat3' , 'V-38452' , 'rpm' ]

- name: V-38452 Low  The system package management tool must verify permissions on all files and directories associated with packages
  shell: rpm --setperms $(rpm -qf {{ item }})
  when: rpm_file_permissions_check.stdout
  with_items: rpm_file_permissions_check.stdout_lines
  tags: [ 'cat3' , 'V-38452' , 'rpm' ]


- name: Check group-ownership on all files and directories associated with packages
  shell: "grep '^......G' /tmp/rhel6stig_rpm_verify | awk '{print $3}' "
  changed_when: false
  register: rpm_group_ownership_check
  failed_when: rpm_group_ownership_check.stderr
  tags: [ 'cat3' , 'V-38453' , 'rpm' ]

- name: V-38453 Low  The system package management tool must verify group-ownership on all files and directories associated with packages
  shell: rpm --setugids $(rpm -qf {{ item }})
  when: rpm_group_ownership_check.stdout
  with_items: rpm_group_ownership_check.stdout_lines
  tags: [ 'cat3' , 'V-38453' , 'rpm' ]


- name: V-38608 Low  The SSH daemon must set a timeout interval on idle sessions
  lineinfile: "state=present backup=yes dest=/etc/ssh/sshd_config regexp='^(#)?ClientAliveInterval' line='ClientAliveInterval 900'"
  tags: [ 'cat3' , 'V-38608' , 'ssh' ]
  notify: restart ssh


- name: Checking integrity of installed files associated with packages
  shell: "awk '$1 ~ /..5/ && $2 != \"c\" ' /tmp/rhel6stig_rpm_verify | awk '{print $2}' "
  changed_when: false
  register: rpm_integrity_check
  failed_when: rpm_integrity_check.stderr
  tags: [ 'cat3' , 'V-38447' , 'rpm' ]

- name: V-38447 Low The system package management tool must verify contents of all files associated with packages
  shell: yum reinstall -y $(rpm -qf {{ item }})
  when: rpm_integrity_check.stdout
  with_items: rpm_integrity_check.stdout_lines
  tags: [ 'cat3' , 'V-38447' , 'rpm' ]


# - name: V-38659 Low The operating system must employ cryptographic mechanisms to protect information in storage



# --- BREAK --- #

- name: V-38533 Low  The system must ignore IPv4 ICMP redirect messages.
  sysctl: name=net.ipv4.conf.default.accept_redirects value=0 state=present reload=yes ignoreerrors=yes
  tags: [ 'cat3' , 'V-38533' , 'icmp_redirects' , 'kerner_parameters' , 'network' ]

- name: Disable TCP timestamp responses
  sysctl: name=net.ipv4.tcp_timestamps value=0 state=present reload=yes ignoreerrors=yes
  tags: [ 'cat3' , 'V-38533' , 'tcp_timestamps' , 'kerner_parameters' , 'network' ]

- name: Use strong MAC algorithms
  lineinfile: "state=present backup=yes dest=/etc/ssh/sshd_config line='MACS    hmac-sha1,umac-64@openssh.com,hmac-ripemd160,hmac-sha2-256,hmac-sha2-512'"
  tags: [ 'cat3' , 'ssh' , 'config' ]
  notify: restart ssh
