# CAT I
- name: "HIGH | V-38677 | AUDIT | The NFS server must not have the insecure file locking option enabled"
  command: grep insecure_locks /etc/exports
  register: nfs_insecure_locking_audit
  ignore_errors: yes
  changed_when: no
  tags:
      - high
      - cat1
      - audit
      - always
      - V-38677
      - nfs

# CAT II
- name: "MEDIUM | V-38499 | AUDIT | The /etc/passwd file must not contain password hashes"
  shell: "awk -F: '($2 != \"x\") {print}' /etc/passwd"
  changed_when: false
  register: etc_password_hash_audit
  tags:
      - medium
      - cat2
      - audit
      - always
      - V-38499
      - passwords

- name: "MEDIUM | V-38500 | AUDIT | The root account must be the only account having a UID of 0"
  shell: "awk -F: '($3 == \"0\") {print}' /etc/passwd | grep -v root"
  changed_when: no
  ignore_errors: yes
  register: users_uid_0_audit
  tags:
      - medium
      - cat2
      - audit
      - always
      - V-38500
      - accounts

- name: "MEDIUM | V-38520 | AUDIT | The operating system must back up audit records on an organization defined frequency onto a different system or media than the system being audited.\n
     \t\tMEDIUM | V-38521 | AUDIT | The operating system must support the requirement to centrally manage the content of audit records generated by organization defined information system components."
  shell: grep -E '^\*\.\*\s*[@:]{1,2}[a-z.:]*' /etc/rsyslog.conf
  changed_when: no
  ignore_errors: yes
  register: rsyslog_log_mgmt_audit
  tags:
      - medium
      - cat2
      - audit
      - always
      - V-38520
      - V-38521
      - rsyslog
      - logging

# CAT III
- name: "LOW | V-38455 | AUDIT | The system must use a separate file system for /tmp"
  shell: mount | grep "on /tmp "
  register: tmp_mounted_audit
  ignore_errors: yes
  changed_when: no
  tags:
      - low
      - cat3
      - audit
      - always
      - V-38455
      - partitions

- name: "LOW | V-38456 | AUDIT | The system must use a separate file system for /var"
  shell: mount | grep "on /var "
  register: var_mounted_audit
  changed_when: no
  ignore_errors: yes
  tags:
      - low
      - cat3
      - audit
      - always
      - V-38456
      - partitions

- name: "LOW | V-38463 | AUDIT | The system must use a separate file system for /var/log"
  shell: mount | grep "on /var/log "
  register: varlog_mounted_audit
  changed_when: no
  ignore_errors: yes
  tags:
      - low
      - cat3
      - audit
      - always
      - V-38463
      - partitions

- name: "LOW | V-38467 | AUDIT | The system must use a separate file system for /var/log/audit"
  shell: mount | grep "on /var/log/audit "
  register: varlogaudit_mounted_audit
  changed_when: no
  ignore_errors: yes
  tags:
      - low
      - cat3
      - audit
      - always
      - V-38467
      - partitions

- name: "LOW | V-38473 | AUDIT | The system must use a separate file system for user home directories"
  shell: mount | grep "on /home "
  register: home_mounted_audit
  changed_when: no
  ignore_errors: yes
  tags:
      - low
      - cat3
      - audit
      - always
      - V-38473
      - partitions

- name: "LOW | V-38681 | AUDIT | All GIDs referenced in /etc/passwd must be defined in /etc/group"
  shell: pwck -r | grep 'no group'
  changed_when: false
  failed_when: false
  register: missing_group_audit
  tags:
      - low
      - cat3
      - audit
      - always
      - V-38681
      - accounts

- name: "LOW | V-38683 | AUDIT | All accounts on the system must have unique user or account names"
  shell: pwck -rq | grep -A1 'duplicate' | grep -v 'duplicate'
  changed_when: false
  failed_when: false
  register: duplicate_account_audit
  tags:
      - low
      - cat3
      - audit
      - always
      - V-38683
      - accounts

- name: " LOW | V-38697 | AUDIT | The sticky bit must be set on all public directories."
  shell: "lsblk | awk '$6 == \"part\" && $7 ~ /\\// {print $NF}' | xargs -I{} find {} -xdev -type d -perm -0002 \\! -perm -1000"
  changed_when: false
  register: stick_bit_public_dir_audit
  tags:
      - low
      - cat3
      - audit
      - always
      - V-38697
      - permissions
      - sticky_bit

- name: " LOW | V-38699 | AUDIT | All public directories must be owned by a system account."
  shell: "lsblk | awk '$6 == \"part\" && $7 ~ /\\// {print $NF}' | xargs -I{} find {} -xdev -type d -perm -0002 -uid +499 -print"
  changed_when: false
  register: system_account_public_dir_audit
  tags:
      - low
      - cat3
      - audit
      - always
      - V-38699
      - permissions
      - public_dir_ownership
