---
# Preliminary tasks that should always be run

# Setup variables based on operating system
- name: Set gpg_key_url for CentOS
  set_fact: gpg_key_url=http://mirror.centos.org/centos/RPM-GPG-KEY-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}
  when: "ansible_distribution == 'CentOS'"
  tags: [ 'cat1' , 'cat2' , 'cat3' ]

- name: Set gpg_key_url for Red Hat 6
  set_fact: gpg_key_url=https://www.redhat.com/security/fd431d51.txt
  when: "ansible_distribution == 'Red Hat'"
  tags: [ 'cat1' , 'cat2' , 'cat3' ]

# List users in order to look files inside each home directory
- name: List users accounts
  command: "awk -F: '{print $1}' /etc/passwd"
  register: users
  changed_when: false
  tags: [ 'cat1' , 'cat2' , 'cat3' ]

- name: List system accounts
  shell: "grep -Ev '/home|root' /etc/passwd | cut -d : -f 1"
  register: system_users
  changed_when: false
  tags: [ 'cat1' , 'cat2' , 'cat3' ]


# Get separate lists of SysV and xinetd services
- name: List SysV services
  shell: "chkconfig --list | sed '/^$/ d ; /xinetd based services:/ d ; /^\t/ d' | awk '{print $1}'"
  register: sysv_services
  changed_when: false
  tags: [ 'cat1' , 'cat2' , 'cat3' ]

- name: List xinetd services
  shell: "chkconfig --list | sed -n '/^\t/,$p' | sed 's/\t//' | cut -d : -f 1"
  register: xinetd_services
  changed_when: false
  tags: [ 'cat1' , 'cat2' , 'cat3' ]


# See if IPv6 is enabled and set a fact
- name: Check if IPv6 is enabled
  shell: ip addr | grep inet6
  changed_when: false
  failed_when: false
  register: rhel6stig_ipv6test
  ignore_errors: yes
  tags: [ 'ipv6' ]

- name: Set ipv6_in_use to 'true'
  set_fact: ipv6_in_use=true
  when: rhel6stig_ipv6test.stdout
  tags: [ 'ipv6' ]