---
- name: restart ntpd
  service: name=ntpd state=restarted

- name: restart ssh
  service: name=sshd state=restarted

- name: restart snmpd
  service: name=snmpd state=restarted

- name: restart xinetd
  service: name=xinetd state=restarted

- name: restart auditd
  service: name=auditd state=restarted

- name: unload usb-storage
  modprobe: name=usb-storage state=absent

- name: update postfix aliases.db
  command: newaliases
